"""Closed enums used by configuration and domain models."""

from enum import StrEnum


class Environment(StrEnum):
    DEMO = "DEMO"
    PRODUCTION = "PRODUCTION"


class ProviderMode(StrEnum):
    NONE = "none"
    FAKE = "fake"
    FIXTURE = "fixture"


class AIProviderMode(StrEnum):
    NONE = "none"
    DETERMINISTIC = "deterministic"
    EXTERNAL = "external"


class BrokerProviderMode(StrEnum):
    NONE = "none"
    ETORO_READ_ONLY = "etoro-read-only"


class OperatingMode(StrEnum):
    OFFLINE_PAPER = "OFFLINE_PAPER"
    ETORO_DEMO = "ETORO_DEMO"
    ETORO_REAL_READ_ONLY = "ETORO_REAL_READ_ONLY"
    SHADOW = "SHADOW"


class ExecutionPolicy(StrEnum):
    ADVISORY = "ADVISORY"
    CONFIRM = "CONFIRM"
    AUTONOMOUS = "AUTONOMOUS"


class EtoroTransportMode(StrEnum):
    SYSTEM_PROXY = "SYSTEM_PROXY"
    DIRECT = "DIRECT"


class Currency(StrEnum):
    EUR = "EUR"
    USD = "USD"


class AssetClass(StrEnum):
    EQUITY = "EQUITY"
    ETF = "ETF"
    CRYPTO = "CRYPTO"
    FOREX = "FOREX"
    INDEX = "INDEX"
    COMMODITY = "COMMODITY"
    BOND = "BOND"
    FUND = "FUND"
    CFD = "CFD"
    FUTURE = "FUTURE"
    OPTION = "OPTION"
    OTHER_DERIVATIVE = "OTHER_DERIVATIVE"
    CASH_EQUIVALENT = "CASH_EQUIVALENT"
    UNKNOWN = "UNKNOWN"


class TradeSide(StrEnum):
    BUY = "BUY"
    SELL = "SELL"


class TradeIntent(StrEnum):
    OPEN = "OPEN"
    INCREASE = "INCREASE"
    REDUCE = "REDUCE"
    CLOSE = "CLOSE"


class SettlementType(StrEnum):
    REAL = "real"
    CFD = "cfd"
    REAL_FUTURES = "realFutures"
    MARGIN_TRADE = "marginTrade"


class HoldingPeriod(StrEnum):
    DAYS = "DAYS"
    WEEKS = "WEEKS"
    MONTHS = "MONTHS"
    YEARS = "YEARS"


class RecommendedAction(StrEnum):
    HOLD = "HOLD"
    OPEN = "OPEN"
    INCREASE = "INCREASE"
    REDUCE = "REDUCE"
    CLOSE = "CLOSE"


class MarketStatus(StrEnum):
    OPEN = "OPEN"
    CLOSED = "CLOSED"
    PRE_MARKET = "PRE_MARKET"
    AFTER_HOURS = "AFTER_HOURS"
    CONTINUOUS_24_7 = "CONTINUOUS_24_7"
    HALTED = "HALTED"
    UNKNOWN = "UNKNOWN"


class AegisRunStatus(StrEnum):
    HOLD = "HOLD"
    EXECUTED_PAPER = "EXECUTED_PAPER"
    REJECTED = "REJECTED"
    FAILED_SAFE = "FAILED_SAFE"


class RiskDecisionStatus(StrEnum):
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"


class RiskViolationCode(StrEnum):
    KILL_SWITCH_ACTIVE = "KILL_SWITCH_ACTIVE"
    LEVERAGE_NOT_ALLOWED = "LEVERAGE_NOT_ALLOWED"
    SHORT_SELLING_NOT_ALLOWED = "SHORT_SELLING_NOT_ALLOWED"
    CFD_NOT_ALLOWED = "CFD_NOT_ALLOWED"
    DERIVATIVE_NOT_ALLOWED = "DERIVATIVE_NOT_ALLOWED"
    MARTINGALE_NOT_ALLOWED = "MARTINGALE_NOT_ALLOWED"
    BLIND_AVERAGING_DOWN = "BLIND_AVERAGING_DOWN"
    ALL_IN_NOT_ALLOWED = "ALL_IN_NOT_ALLOWED"
    MAX_POSITION_EXPOSURE_EXCEEDED = "MAX_POSITION_EXPOSURE_EXCEEDED"
    MAX_TRADE_SIZE_EXCEEDED = "MAX_TRADE_SIZE_EXCEEDED"
    MIN_CASH_RESERVE_BREACHED = "MIN_CASH_RESERVE_BREACHED"
    MAX_DAILY_TRADES_EXCEEDED = "MAX_DAILY_TRADES_EXCEEDED"
    STALE_PRICE = "STALE_PRICE"
    MARKET_DATA_UNAVAILABLE = "MARKET_DATA_UNAVAILABLE"
    NEWS_DATA_UNAVAILABLE = "NEWS_DATA_UNAVAILABLE"
    INVALID_INSTRUMENT_METADATA = "INVALID_INSTRUMENT_METADATA"
    DUPLICATE_ORDER = "DUPLICATE_ORDER"
    INCONSISTENT_PORTFOLIO_STATE = "INCONSISTENT_PORTFOLIO_STATE"
    INCONSISTENT_API_STATE = "INCONSISTENT_API_STATE"
    CRITICAL_OPERATIONAL_ERROR = "CRITICAL_OPERATIONAL_ERROR"
    CONFIDENCE_BELOW_MINIMUM = "CONFIDENCE_BELOW_MINIMUM"
    INVALID_CONFIDENCE_SEMANTICS = "INVALID_CONFIDENCE_SEMANTICS"
    CURRENCY_MISMATCH = "CURRENCY_MISMATCH"
    INVALID_TRADE_DIRECTION = "INVALID_TRADE_DIRECTION"


class AuditEventType(StrEnum):
    AEGIS_RUN_STARTED = "AEGIS_RUN_STARTED"
    AEGIS_RUN_COMPLETED = "AEGIS_RUN_COMPLETED"
    PORTFOLIO_READ = "PORTFOLIO_READ"
    MARKET_DATA_READ = "MARKET_DATA_READ"
    NEWS_READ = "NEWS_READ"
    AGENT_ANALYSIS_STARTED = "AGENT_ANALYSIS_STARTED"
    AGENT_ANALYSIS_COMPLETED = "AGENT_ANALYSIS_COMPLETED"
    AGENT_OUTPUT_INVALID = "AGENT_OUTPUT_INVALID"
    PROPOSAL_CREATED = "PROPOSAL_CREATED"
    PROPOSAL_REJECTED = "PROPOSAL_REJECTED"
    RISK_EVALUATED = "RISK_EVALUATED"
    RISK_APPROVED = "RISK_APPROVED"
    RISK_REJECTED = "RISK_REJECTED"
    PAPER_EXECUTION_ADMITTED = "PAPER_EXECUTION_ADMITTED"
    PAPER_EXECUTION_COMPLETED = "PAPER_EXECUTION_COMPLETED"
    PAPER_EXECUTION_REJECTED = "PAPER_EXECUTION_REJECTED"
    PROVIDER_FAILURE = "PROVIDER_FAILURE"
    KILL_SWITCH_CHANGED = "KILL_SWITCH_CHANGED"
