"""Version labels for deterministic research and safety records."""

SCANNER_VERSION = "universal-scanner-v1"
RANKING_VERSION = "opportunity-ranking-v1"
STRATEGY_VERSION = "aegis-multi-asset-v2"
BROKER_ADAPTER_VERSION = "etoro-read-only-adapter-v1"
FEATURE_ENGINE_VERSION = "market-feature-engine-v1"
REGIME_ENGINE_VERSION = "market-regime-engine-v1"
STRATEGY_PROFILE_VERSION = "asset-strategy-profile-v1"
STRATEGY_ENSEMBLE_VERSION = "strategy-ensemble-v1"
OPPORTUNITY_SCORE_VERSION = "aegis-opportunity-score-v1"
INTELLIGENCE_ENGINE_VERSION = "live-intelligence-engine-v1"
HISTORICAL_DATA_VERSION = "historical-data-layer-v1"
NEWS_MODEL_VERSION = "news-model-v1"
OPPORTUNITY_SCORE_V2_VERSION = "aegis-opportunity-score-v2"
VALIDATION_ENGINE_VERSION = "strategy-validation-engine-v1"
